### ISSUE TITLE
Null node can cause segfault

### ISSUE THREAD

**Issue by bgandon** [krishicks/yaml-patch#8]
Document:
```yaml
plip:
  plop:
    plaf: ~
```

Patch:
```yaml
- path: /plip/plop/plaf/plaf
  op: remove
```

Result:
```
$ ./yaml-patch -o test-patch2.yml < test-doc2.yml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x113184c]

goroutine 1 [running]:
github.com/krishicks/yaml-patch.tryRemove(0x1220300, 0xc42008a088, 0xc4200864c0, 0xffffffffffffffff, 0xc4200d7c58)
	/home/pilot/go/src/github.com/krishicks/yaml-patch/operation.go:101 +0x10c
github.com/krishicks/yaml-patch.(*Operation).Perform(0xc4200864c0, 0x1220300, 0xc42008a088, 0x11466c0, 0xc42009a760)
	/home/pilot/go/src/github.com/krishicks/yaml-patch/operation.go:70 +0x318
github.com/krishicks/yaml-patch.Patch.Apply(0xc420086400, 0x1, 0x1, 0xc4200f0600, 0x52, 0x600, 0x600, 0x1, 0x17, 0xc4200984b0, ...)
	/home/pilot/go/src/github.com/krishicks/yaml-patch/patch.go:52 +0x56c
main.main()
	/home/pilot/go/src/github.com/krishicks/yaml-patch/cmd/yaml-patch/main.go:50 +0x58c
```

Tested with release `v0.0.10` on Darwin.

I'll really skeptical about [these lines of code](https://github.com/krishicks/yaml-patch/blob/master/pathfinder.go#L67-L71): how could a path match a container or its parent?

**Comment by krishicks** [comment]
I am unsure of why that code ended up that way. One positive test case seemed to be erroneously there, so I moved it to a negative case and removed the code.

Thanks for the find!
